export const routes = {
    defaults: "/",
    page404: "/page-not-found",
    help: "/help",
    login: "/login",
    register: "/register",
    recover: "/recover",
    createSusu: "/create-susu",
    joinSusu: "/join-susu",
    settings: "/settings",
    request: "/request",
    manage: "/manage",
    welcome: "/welcome",
    myAccount: "/my-account",
}