export const routes = {
    defaults: "/",
    test: "/test",
    page404: "/page-not-found",
    help: "/help",
    param: "/join-by-link:id",
    login: "/login",
    register: "/register",
    recover: "/recover",
    createSusu: "/create-susu",
    joinSusu: "/join-susu",
    settings: "/settings",
    request: "/request",
    manage: "/manage",
    welcome: "/welcome",
    myAccount: "/my-account",
    mobileMenu: "/mobile/menu",
}